### ISSUE TITLE
Upgrade fisherman > 2.5

### ISSUE THREAD

**Issue by bucaran** [boj/dotfiles#1]
Hi @boj 

Recent changes in fisherman (one month or so), were too large that we broke backward compatibility. While you could run `fisher update` and then fix the mess, I recommend instead removing fisherman entirely (see https://github.com/fisherman/fisherman/issues/241) and upgrading to its latest. 

The new fisherman is super easy to use and install (more reliable too), but if have any issues, I am just a ping away.

**Comment by boj** [comment]
I ended up building a new work machine and rebuilding my personal machine within the last couple weeks and noticed it was a completely different system.  Thanks.
